select top 20 * from customer

-- Q1. What is the total revenue generated by male vs female customers?

select gender, SUM(purchase_amount) as Revenue
from customer
group by gender

-- Q2. Which customerss used a discount but still spent more than the average amount purchased?
select AVG(purchase_amount) from customer --59

select customer_id, purchase_amount
from customer 
where discount_applied='Yes' and purchase_amount >=(select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 prodcuts with the highest average review rating?
select top 5 item_purchased, Round(AVG(review_rating),2) as "Product Average Rating"
from customer
group by item_purchased
order by [Product Average Rating] desc

-- Q4. Compare the average purchase amounts between standard and express shipping
select shipping_type,
AVG(purchase_amount) as "Average Purchase Amount" 
from customer
where shipping_type ='Standard' or shipping_type ='Express' -- shipping_type in ('Standard' , 'Express')
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non subscribers.

select subscription_status,
Count(customer_id) as [Total Customers],
AVG(purchase_amount) as [Average Spend],
SUM(purchase_amount) as [Total Revenue]
from customer
group by subscription_status
order by [Total Revenue], [Average Spend] desc

--Q6. Which 5 products have the highest percentage of purchases with discount applied?
select top 5 item_purchased,
round(100*SUM(CASE WHEN discount_applied='Yes' then 1 else 0 end)/count(*),2) as [Discount_rate] -- out of everytime it was sold how many times ( in percent) was it sold when discount was applied
from customer
group by item_purchased
order by [Discount_rate] desc
-- helps us in analyzing which product are sold more when they are on a discount or which products rely heavily on discount


-- Q7. Segment custommers into New, Returning or Loyal based on their total number of previous purchases,
-- and show the count of each segment.
select MIN(previous_purchases) from customer

with customer_type as (
select customer_id, previous_purchases,
Case
    when previous_purchases=1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment, count(*) as [Number of Customers]
from customer_type
group by customer_segment
order by [Number of Customers] desc

-- Q8 What are the top 3 most purchased products within each category?
with item_counts as (
select category, 
item_purchased,
count(customer_id) as [Total Purchases],
Row_Number() OVER(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, [Total Purchases]
from item_counts
where item_rank <=3

-- Q9. Are Customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as [Repeat Buyers] 
from customer
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?

select age_group, sum(purchase_amount) as [Total Revenue]
from customer
group by age_group
order by [Total Revenue] desc





 




